on:
  workflow_dispatch:
    inputs:
      Kubeslice_Controller:
        description: 'Kubeslice Controller'
        required: true 
        type: boolean
      kubeslice_controller_package_path:
        description: 'Kubeslice Controller Package Path'
        required: false 
        type: string
      Kubeslice_Woker:
        description: 'Kubeslice Worker'
        required: true 
        type: boolean 
      kubeslice_worker_package_path:
        description: 'Kubeslice Worker Package Path'
        required: false 
        type: string

jobs:
  update-worker-to-rancher-partner-chart:
    if:  ${{ inputs.Kubeslice_Woker }} 
    runs-on: ubuntu-latest
    steps:
      - name: Worker
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          repository: basic-techno/partner-charts
          path: 'worker'
          ref: 'avesha'
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Rancher
        shell: bash
        run: | 
          cd worker
          make 
          export PACKAGE=kubeslice-worker
          cd packages/kubeslice-worker
          cat << EOF > package.yaml
          url: "${{ inputs.kubeslice_worker_package_path }}"
          packageVersion: 00
          EOF
          cat package.yaml
          cd ../../
          export PACKAGE=kubeslice-worker
          make prepare
          git config remote.origin.url https://${{ secrets.PAT }}@github.com/basic-techno/partner-charts.git
          git config --global user.email "vivek.bangare2492@gmail.com"
          git config --global user.name "basic-techno"
          git add -A && git commit -m "downloading worker chart"
          export PACKAGE=kubeslice-worker
          make charts
          echo "**********************"
          echo "Charts Created"
          echo "**********************"
          git add -A && git commit -m "creating worker chart"
          export PACKAGE=kubeslice-worker
          echo "**********************"
          echo "Charts Cleaning"
          echo "**********************"
          make clean
          git add -A && git commit -m "cleaning worker chart"
          echo "**********************"
          echo "Charts Validation"
          echo "**********************"
          export PACKAGE=kubeslice-worker
          make validate
          echo "**********************"
          echo "Publishing Charts"
          echo "**********************"
          git push -u origin avesha
  update-controller-to-rancher-partner-chart:
    if:  ${{ inputs.Kubeslice_Controller }}
    runs-on: ubuntu-latest
    steps:
      - name: Controller
        run: echo ${{ inputs.Kubeslice_Controller }}
  
